const imageSet = (slug, name, alt) => ({
  small: `/leona-li/assets/images/work/projects/${slug}/${name}-900.webp`,
  large: `/leona-li/assets/images/work/projects/${slug}/${name}-1800.webp`,
  alt,
});

const gallery = (slug, title, count) => Array.from({ length: count }, (_, index) => {
  const number = String(index + 1).padStart(2, '0');
  return imageSet(slug, number, `${title} — editorial image ${number}`);
});

const sourceImage = (slug, filename, alt) => ({
  small: `/leona-li/assets/images/work/projects/${slug}/${filename.replace(/\.[^.]+$/, '')}-900.webp`,
  large: `/leona-li/assets/images/work/projects/${slug}/${filename.replace(/\.[^.]+$/, '')}-1800.webp`,
  alt,
});

const sourceGallery = (slug, title, filenames) => filenames.map((filename, index) => ({
  ...sourceImage(slug, filename, `${title} — project image ${String(index + 1).padStart(2, '0')}`),
}));

export const fashionProjects = [
  {
    number: '01',
    slug: 'between-spaces',
    title: 'Between Spaces',
    category: 'Fashion Editorial / Visual Study',
    filter: 'fashion',
    year: '2025',
    description: 'A visual study of presence and absence, where architecture becomes an extension of the human form.',
    cover: imageSet('between-spaces', 'cover', 'Between Spaces project cover'),
    gallery: gallery('between-spaces', 'Between Spaces', 4),
  },
  {
    number: '02',
    slug: 'waving',
    title: 'Waving',
    category: 'Fashion Editorial',
    filter: 'fashion',
    year: '2025',
    description: 'An exploration of movement, distance and the quiet relationship between the human body and surrounding space.',
    cover: imageSet('waving', 'cover', 'Waving project cover'),
    gallery: gallery('waving', 'Waving', 8),
  },
  {
    number: '03',
    slug: 'echo',
    title: 'Echo',
    category: 'Fashion Editorial',
    filter: 'fashion',
    year: '2025',
    description: 'A dialogue between light, texture and movement, capturing moments that exist between reality and memory.',
    cover: imageSet('echo', 'cover', 'Echo project cover'),
    gallery: gallery('echo', 'Echo', 4),
  },
  {
    number: '04',
    slug: 'traces-of-light',
    title: 'Traces of Light',
    category: 'Fashion Editorial',
    filter: 'fashion',
    year: '2025',
    description: 'An observation of natural light, organic forms and the evolving relationship between human and environment.',
    cover: imageSet('traces-of-light', 'cover', 'Traces of Light project cover'),
    gallery: gallery('traces-of-light', 'Traces of Light', 5),
  },
  {
    number: '05',
    slug: 'urban-silence',
    title: 'Urban Silence',
    category: 'Fashion Editorial',
    filter: 'fashion',
    year: '2025',
    description: 'A study of urban solitude, movement and the unexpected poetry found in everyday surroundings.',
    cover: imageSet('urban-silence', 'cover', 'Urban Silence project cover'),
    gallery: gallery('urban-silence', 'Urban Silence', 4),
  },
  {
    number: '06',
    slug: 'daydream',
    title: 'Daydream',
    category: 'Fashion Story',
    filter: 'fashion',
    year: '2025',
    description: 'A dreamlike narrative exploring softness, emotion and fragments of everyday imagination.',
    cover: imageSet('daydream', 'cover', 'Daydream project cover'),
    gallery: gallery('daydream', 'Daydream', 6),
  },
];

export const personalPortraitProjects = [
  {
    number: '01',
    slug: 'within-the-light',
    title: 'Within The Light',
    category: 'Personal Portraits',
    filter: 'portrait',
    description: 'An intimate portrait study focused on presence, natural light and quiet gesture.',
    cover: imageSet('within-the-light', 'cover', 'Within The Light project cover'),
    gallery: gallery('within-the-light', 'Within The Light', 2),
  },
  {
    number: '02',
    slug: 'the-white-chapter',
    title: 'The White Chapter',
    category: 'Personal Portraits',
    filter: 'portrait',
    description: 'An editorial portrait series focused on intimacy, elegance and quiet personal rituals.',
    cover: imageSet('the-white-chapter', 'cover', 'The White Chapter project cover'),
    gallery: gallery('the-white-chapter', 'The White Chapter', 20),
  },
  {
    number: '03',
    slug: 'between-us',
    title: 'Between Us',
    category: 'Personal Portraits',
    filter: 'portrait',
    description: 'A portrait study of connection and the subtle exchange between two people.',
    cover: imageSet('between-us', 'cover', 'Between Us project cover'),
    gallery: gallery('between-us', 'Between Us', 11),
  },
  {
    number: '04',
    slug: 'parisian-silence',
    title: 'Parisian Silence',
    category: 'Personal Portraits',
    filter: 'portrait',
    description: 'A restrained portrait study of gesture, identity and atmosphere in Paris.',
    cover: imageSet('parisian-silence', 'cover', 'Parisian Silence project cover'),
    gallery: gallery('parisian-silence', 'Parisian Silence', 2),
  },
  {
    number: '05',
    slug: 'red-study',
    title: 'Red Study',
    category: 'Personal Portraits',
    filter: 'portrait',
    description: 'A colour-led portrait study of confidence, expression and the visual impact of red.',
    cover: imageSet('red-study', 'cover', 'Red Study project cover'),
    gallery: gallery('red-study', 'Red Study', 2),
  },
  {
    number: '06',
    slug: 'between-dreams',
    title: 'Between Dreams',
    category: 'Personal Portraits',
    filter: 'portrait',
    description: 'An abstract portrait study using movement, layered imagery and natural forms.',
    cover: imageSet('between-dreams', 'cover', 'Between Dreams project cover'),
    gallery: gallery('between-dreams', 'Between Dreams', 2),
  },
];

export const commercialBrandCampaigns = [
  {
    number: '01',
    slug: 'summer-narrative',
    title: 'Summer Narrative',
    category: 'Lifestyle Campaign',
    filter: 'commercial',
    description: 'Lifestyle campaign image series.',
    cover: imageSet('summer-narrative', 'cover', 'Summer Narrative campaign cover'),
    gallery: gallery('summer-narrative', 'Summer Narrative', 4),
  },
  {
    number: '02',
    slug: 'inside-brand-visual-story',
    title: 'Inside Brand Visual Story',
    category: 'Fashion Campaign',
    filter: 'commercial',
    description: 'Fashion campaign image series.',
    cover: imageSet('inside-brand-visual-story', 'cover', 'Inside Brand Visual Story campaign cover'),
    gallery: gallery('inside-brand-visual-story', 'Inside Brand Visual Story', 6),
  },
  {
    number: '03',
    slug: 'black-attitude',
    title: 'Black Attitude',
    category: 'Fashion Campaign',
    filter: 'commercial',
    description: 'Fashion campaign image series.',
    cover: imageSet('black-attitude', 'cover', 'Black Attitude campaign cover'),
    gallery: gallery('black-attitude', 'Black Attitude', 2),
  },
  {
    number: '04',
    slug: 'runway-stories',
    title: 'Runway Stories',
    category: 'Runway Visual Story',
    filter: 'commercial',
    description: 'Runway visual story image series.',
    cover: imageSet('runway-stories', 'cover', 'Runway Stories campaign cover'),
    gallery: gallery('runway-stories', 'Runway Stories', 6),
  },
];

export const commercialSelectedImages = [
  imageSet('selected-commercial-images', '01', 'Selected Works — red background portrait'),
  imageSet('selected-commercial-images', '02', 'Selected Works — green architectural portrait'),
  imageSet('selected-commercial-images', '03', 'Selected Works — balcony fashion portrait'),
  imageSet('selected-commercial-images', '04', 'Selected Works — grass lifestyle image'),
  imageSet('selected-commercial-images', '05', 'Selected Works — interior sofa portrait'),
  imageSet('selected-commercial-images', '08', 'Selected Works — white dress image'),
  imageSet('selected-commercial-images', '06', 'Selected Works — beauty close-up portrait'),
  imageSet('selected-commercial-images', '07', 'Selected Works — beauty detail portrait'),
];

export const commercialStillLifeCollections = [
  {
    number: '01',
    title: 'Product Studies',
    description: 'Commercial product imagery exploring material, texture and visual composition through controlled lighting.',
    images: gallery('product-studies', 'Product Studies', 7),
  },
  {
    number: '02',
    title: 'Beauty Still Life',
    description: 'Beauty and still-life images focusing on detail, atmosphere and refined visual presentation.',
    images: gallery('beauty-objects', 'Beauty Still Life', 2),
  },
];

export const commercialEditorialProjects = [
  {
    number: '01',
    slug: 'calling-for-love',
    title: 'Calling for Love',
    category: 'Editorial Story',
    filter: 'commercial',
    description: 'An editorial portrait series exploring emotion, intimacy and visual storytelling.',
    cover: imageSet('calling-for-love', 'cover', 'Calling for Love editorial cover'),
    gallery: gallery('calling-for-love', 'Calling for Love', 5),
  },
  {
    number: '02',
    slug: 'questions-of-existence',
    title: 'Questions of Existence',
    category: 'Editorial Story',
    filter: 'commercial',
    description: 'A conceptual editorial exploring identity, human experience and visual narratives.',
    cover: imageSet('questions-of-existence', 'cover', 'Questions of Existence editorial cover'),
    gallery: gallery('questions-of-existence', 'Questions of Existence', 8),
  },
  {
    number: '03',
    slug: 'in-a',
    title: 'In a ___',
    category: 'Editorial Story',
    filter: 'commercial',
    description: 'A visual exploration built around atmosphere, space and personal expression.',
    cover: imageSet('in-a', 'cover', 'In a ___ editorial cover'),
    gallery: gallery('in-a', 'In a ___', 7),
  },
  {
    number: '04',
    slug: 'time',
    title: 'Time',
    category: 'Editorial Story',
    filter: 'commercial',
    description: 'An editorial study exploring moments, memory and visual rhythm.',
    cover: imageSet('time', 'cover', 'Time editorial cover'),
    gallery: gallery('time', 'Time', 4),
  },
  {
    number: '05',
    slug: 'time-traveller',
    title: 'Time Traveller',
    category: 'Editorial Story',
    filter: 'commercial',
    description: 'A fashion editorial blending contemporary styling with a sense of nostalgia and imagination.',
    cover: imageSet('time-traveller', 'cover', 'Time Traveller editorial cover'),
    gallery: gallery('time-traveller', 'Time Traveller', 3),
  },
  {
    number: '06',
    slug: 'calling-for-spring',
    title: 'Calling for Spring',
    category: 'Editorial Story',
    filter: 'commercial',
    description: 'An editorial story capturing seasonal transition, emotion and visual freshness.',
    cover: imageSet('calling-for-spring', 'cover', 'Calling for Spring editorial cover'),
    gallery: gallery('calling-for-spring', 'Calling for Spring', 3),
  },
];

export const commercialProjects = [...commercialBrandCampaigns, ...commercialEditorialProjects];

const karlCampaignImages = sourceGallery('karl-lagerfeld-ss25', 'Karl Lagerfeld SS25 Campaign', [
  'campaign-01.jpg',
  'campaign-02.jpg',
  'campaign-03.jpg',
]);

const karlLookbookImages = sourceGallery('karl-lagerfeld-ss25', 'Karl Lagerfeld SS25 Lookbook', [
  'lookbook-01.jpg',
  'lookbook-05.jpg',
  'lookbook-06.jpg',
  'lookbook-07.jpg',
  'lookbook-08.jpg',
  'lookbook-09.jpg',
  'lookbook-10.jpg',
  'lookbook-11.jpg',
  'lookbook-12.jpg',
]);

export const creativeProductionProjects = [
  {
    number: '01',
    slug: 'karl-lagerfeld-ss25',
    title: 'Karl Lagerfeld — SS25 Campaign & Lookbook',
    client: 'Karl Lagerfeld',
    projectName: 'SS25 Campaign & Lookbook',
    category: 'Fashion Lookbook / Campaign Production',
    filter: 'creative-production',
    year: '2025',
    roleSummary: 'Creative Production / Visual Direction Support / Production Coordination / On-set Execution / Photography Supervision',
    brandContext: 'Karl Lagerfeld is a global fashion house with a distinctive, modern visual identity. The SS25 production connected campaign impact with the relaxed rhythm of the seasonal lookbook.',
    projectOverview: 'Supported the translation of the SS25 collection into a cohesive campaign and lookbook language through creative coordination, production planning and on-set collaboration.',
    description: 'A fashion campaign project developed for Karl Lagerfeld SS25 collection, supporting the translation of seasonal brand vision into a cohesive visual language through creative coordination, production workflow and on-set collaboration.',
    cover: sourceImage('karl-lagerfeld-ss25', 'cover.jpg', 'Karl Lagerfeld SS25 Campaign and Lookbook cover'),
    gallery: [...karlCampaignImages, ...karlLookbookImages],
    sections: [
      {
        title: 'Karl Lagerfeld SS25 Campaign',
        description: 'A fashion campaign project developed for Karl Lagerfeld SS25 collection, supporting the translation of seasonal brand vision into a cohesive visual language through creative coordination, production workflow and on-set collaboration.',
        roles: ['Production Coordination', 'Visual Direction Support', 'On-set Execution', 'Photography Supervision'],
        images: karlCampaignImages,
      },
      {
        title: 'Karl Lagerfeld SS25 Lookbook',
        description: 'Developed and coordinated the visual execution of Karl Lagerfeld SS25 Lookbook, translating the collection concept into a cohesive visual story through production planning, model direction, lighting collaboration and on-set creative supervision.',
        roles: ['Creative Production', 'Visual Direction Support', 'Shooting Plan Development', 'Vendor Communication', 'Model Direction', 'On-set Art Coordination', 'Photography Supervision'],
        process: ['Visual Development', 'Production Coordination', 'On-set Direction'],
        experience: [
          'Participated in early visual discussions based on the new collection.',
          'Developed shooting proposals and visual references.',
          'Helped define visual direction and execution requirements.',
          'Coordinated suppliers and production communication.',
          'Supervised visual consistency across the shoot.',
          'Communicated with models in English around mood, attitude and performance.',
          'Collaborated with the photographer on lighting and image atmosphere.',
          'Maintained a consistent relaxed resort feeling throughout the lookbook.',
        ],
        images: karlLookbookImages,
      },
    ],
  },
  {
    number: '02',
    slug: 'shokz-product-campaign',
    title: 'Shokz — Product Experience',
    client: 'Shokz',
    projectName: 'Product Experience',
    category: 'Technology / Lifestyle Storytelling',
    filter: 'creative-production',
    year: '2025',
    roleSummary: 'Visual Concept Development / Creative Production / Photography',
    description: 'A product experience project connecting technology, movement and everyday lifestyle through visual storytelling.',
    brandContext: 'Shokz is a global technology brand known for innovative open-ear audio products, combining sound, movement and everyday lifestyle experiences.',
    projectOverview: 'This project focused on translating Shokz’s product innovation into a visual story connecting technology with active lifestyles. Through lifestyle-driven imagery and product storytelling, the production communicated the balance between functionality, comfort and modern movement.',
    roles: ['Visual Concept Development', 'Creative Production', 'Photography', 'Lifestyle Storytelling', 'Production Coordination'],
    cover: sourceImage('shokz-product-campaign', 'cover.jpg', 'Shokz Product Experience cover'),
    gallery: sourceGallery('shokz-product-campaign', 'Shokz Product Experience', ['01.jpg', '02.jpg', '03.jpg']),
  },
  {
    number: '03',
    slug: 'fila-urban-lifestyle',
    title: 'FILA — Urban Movement',
    client: 'FILA',
    projectName: 'Urban Movement',
    category: 'Campaign Production / Lifestyle',
    filter: 'creative-production',
    year: '2025',
    roleSummary: 'Visual Direction Support / Campaign Production / Photography',
    description: 'A campaign study connecting movement, urban environment and contemporary lifestyle identity.',
    brandContext: 'FILA is a global sportswear brand blending athletic heritage with contemporary fashion culture.',
    projectOverview: 'This project explored the relationship between movement, urban environment and lifestyle identity, creating visual narratives that connect performance and everyday expression.',
    roles: ['Visual Direction Support', 'Campaign Production', 'Photography'],
    cover: sourceImage('fila-urban-lifestyle', 'cover.JPG', 'FILA Urban Movement cover'),
    gallery: sourceGallery('fila-urban-lifestyle', 'FILA Urban Movement', ['01.JPG', '02.JPG', '03.JPG', '04.JPG', '05.JPG', '06.JPG', '07.JPG', '08.JPG']),
  },
  {
    number: '04',
    slug: 'infinite-wildness',
    title: 'Infinite Wildness — Visual Concept',
    client: 'Self-Initiated',
    projectName: 'Visual Concept',
    category: 'Conceptual Creative Project',
    filter: 'creative-production',
    year: '2025',
    roleSummary: 'Creative Concept / Visual Planning / Photography',
    description: 'A self-initiated visual concept exploring nature, freedom and human connection.',
    brandContext: 'Infinite Wildness is positioned as a conceptual creative study rather than a commercial campaign, allowing visual research and image-making to lead the project.',
    projectOverview: 'A visual exploration inspired by nature, freedom and human connection, developed through conceptual thinking, location research and visual storytelling.',
    roles: ['Creative Concept', 'Visual Planning', 'Photography'],
    cover: sourceImage('infinite-wildness', 'cover.jpg', 'Infinite Wildness Visual Concept cover'),
    gallery: sourceGallery('infinite-wildness', 'Infinite Wildness Visual Concept', ['01.jpg', '02.jpg', '03.jpg', '04.jpg']),
  },
];

export const projects = [
  ...fashionProjects,
  ...personalPortraitProjects,
  ...commercialProjects,
  ...creativeProductionProjects,
];

export const getProject = (slug) => projects.find((project) => project.slug === slug);
